#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
pushd $script_dir

echo "------------------------------------------------------------"
echo "Gradle 8.7 generation of verification metadata"
echo "(Originally generated by Gradle 8.6)"
echo "------------------------------------------------------------"

./gradlew --write-verification-metadata pgp,sha256 help --offline

popd